blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/', views.PostListView.as_view(), name='posts'),
    path('post/<int:pk>', views.PostDetailView.as_view(), name='post-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('post/<int:pk>/comment', views.comment, name='comment'),
]

urlpatterns += [
    path('comment/create/', views.CommentCreate.as_view(), name='comment-create'),
]

diyblog/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# Use include() to add paths from the catalog application
from django.urls import include

urlpatterns += [
    path('blog/', include('blog.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='blog/', permanent=True)),
]

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField('date', auto_now_add=True)
    title = models.CharField(max_length=200, help_text='Enter the title of your post')
    content = models.TextField(max_length=8000, help_text='Enter the content of your post')

    class Meta:
        ordering = ['date']

    def __str__(self):
        return f'{self.author} ({self.date}) - {self.title}'

    def get_absolute_url(self):
        return reverse('post-detail', args=[str(self.id)])

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField('date', auto_now_add=True)
    content = models.TextField(max_length=2000, help_text='Enter the content of your comment')
    post = models.ForeignKey('Post', on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['date']

    def __str__(self):
        return f'{self.user} ({self.date}) : {self.content}'

class Author(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    bio = models.TextField(max_length=8000, help_text='Enter your bio')

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])

blog/forms.py
from django import forms

"""
class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")
"""

class CommentForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea, help_text="Enter your comment")

blog/views.py
from django.shortcuts import render

# Create your views here.

from .models import Post, Comment, Author

def index(request):
    num_posts = Post.objects.count()
    num_comments = Comment.objects.count()
    num_authors = Author.objects.count()

    context = {
        'num_posts': num_posts,
        'num_comments': num_comments,
        'num_authors': num_authors,
    }

    return render(request, 'index.html', context=context)

from django.views import generic

class PostListView(generic.ListView):
    model = Post
    paginate_by = 5

class PostDetailView(generic.DetailView):
    model = Post

class CommentListView(generic.ListView):
    model = Comment

class AuthorListView(generic.ListView):
    model = Author
    paginate_by = 5

class AuthorDetailView(generic.DetailView):
    model = Author

import datetime

from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
import datetime

from blog.forms import CommentForm

@login_required
def comment(request, pk):
    """View function for renewing a specific BookInstance by librarian."""
    post = get_object_or_404(Post, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = CommentForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            # book_instance.due_back = form.cleaned_data['renewal_date']
            comment = Comment(user=request.user, post=post, content=form.cleaned_data['content'])
            comment.save()

            # redirect to a new URL:
            return HttpResponseRedirect(post.get_absolute_url())

    # If this is a GET (or any other method) create the default form.
    else:
        """
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date})
        """
        form = CommentForm()

    context = {
        'form': form,
        'post': post,
    }

    return render(request, 'blog/comment.html', context)

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView
from django.urls import reverse

class CommentCreate(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ['content']

    def form_valid(self, form):
        """
        Add author and associated blog to form data before setting it as valid (so it is saved to model)
        """
        #Add logged-in user as author of comment
        form.instance.author = self.request.user
        #Associate comment with blog based on passed id
        form.instance.blog=get_object_or_404(Blog, pk = self.kwargs['pk'])
        # Call super-class form validation behavior
        return super(BlogCommentCreate, self).form_valid(form)

blog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>DIY Blog</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'posts' %}">All blogs</a></li>
          <li><a href="{% url 'authors' %}">All bloggers</a></li>
        </ul>
        <ul class="sidebar-nav">
          {% if user.is_authenticated %}
            <li>User: {{ user.get_username }}</li>
            <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
          {% else %}
            <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
          {% endif %}
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}
        {% block pagination %}
        {% if is_paginated %}
        <div class="pagination">
          <span class="page-links">
            {% if page_obj.has_previous %}
            <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <span class="page-current">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
            <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
          </span>
        </div>
        {% endif %}
        {% endblock %}
      </div>
    </div>
  </div>
</body>
</html>

blog/templates/blog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
	<h1>Blogger: {{ author.user }}</h1>

	<h4>Bio</h4>
	<p>{{ author.bio }}</p>

	<h4>Blogs list</h4>
	{% if author.post_set.all %}
		<ul>
			{% for post in author.post_set.all %}
				<li>
					<a href={{ post.get_absolute_url }}>{{ post.title }}</a> ({{ post.date }})
				</li>
			{% endfor %}
		</ul>
	{% else %}
		<p>This blogger has no blog posts.</p>
	{% endif %}

{% endblock %}

blog/templates/blog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Blogger List</h1>
  {% if author_list %}
  <ul>
    {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.user }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no bloggers.</p>
  {% endif %}
{% endblock %}

blog/templates/blog/comment.html
{% extends "base_generic.html" %}

{% block content %}
<p>Post your comment for: <a href={{ post.get_absolute_url }}>{{post.title}}</a></p>
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {% comment %}{{ form.as_table }}{% endcomment %}
    {{ form }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

blog/templates/blog/comment_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ post.title }}</h1>

  <p><strong>Post date:</strong> {{ post.date }}</p>
  <p><strong>Author:</strong> <a href={{ post.author.get_absolute_url }}>{{ post.author }}</a></p>
  <p><strong>Description:</strong>
  <p>{{ post.content }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Comments</h4>

    {% for comment in post.comment_set.all %}
      <hr>
			<p>{{ comment.user }} ({{ comment.date }})</p>
			<p>{{ comment.content }}</p>
    {% endfor %}
		<hr>
    <a href={% url 'comment' post.id %}>Add a new comment</a>
  </div>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Blog Post List</h1>
  {% if post_list %}
  <ul>
    {% for post in post_list %}
      <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a> ({{post.date}}) - <a href="{{post.author.get_absolute_url}}">{{post.author}}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no blog posts.</p>
  {% endif %}
{% endblock %}

blog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>DIY Blog Home</h1>
	<p>Welcome to DIY Blog, a website developed for an <a
      href="https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/django_assessment_blog">Assessment</a>.</p>
  <h2>Dynamic content</h2>
  <p>The blog has the following record counts:</p>
  <ul>
    <li><strong>Posts:</strong> {{ num_posts }}</li>
    <li><strong>Comments:</strong> {{ num_comments }}</li>
    <li><strong>Bloggers:</strong> {{ num_authors }}</li>
  </ul>
{% endblock %}